---
# version: "3.7"

networks:
  proxy:
    driver: bridge
    external: true

services:
  mariadb-master:
    image: ${DOCKER_REGISTRY?}/${DOCKER_NAMESPACE?}/${DOCKER_IMAGE?}:${DOCKER_IMAGE_TAG?}
    restart: unless-stopped
    ports:
      - "${DATABASE_DB_PORT}:3306"
    networks:
      - proxy
    volumes:
      - ${DATABASE_CONFIG_DIR}/my_custom.cnf:/opt/bitnami/mariadb/conf/my_custom.cnf:ro
      - ${DATABASE_DATA_DIR}/development_db:/bitnami/mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
      - MARIADB_USER=${DATABASE_USER}
      - MARIADB_PASSWORD=${DATABASE_PASSWORD}
      - MARIADB_DATABASE=${DATABASE_DATABASE_NAME}
    healthcheck:
      test: ["CMD", "/opt/bitnami/scripts/mariadb/healthcheck.sh"]
      interval: 15s
      timeout: 5s
      retries: 6
