version: "2.1"

networks:
  proxy:
    driver: bridge
    external: true
  secure:
    driver: bridge
    external: true

services:
  mariadb-master:
    image: ${DOCKER_REGISTRY?}/${DOCKER_NAMESPACE?}/${DOCKER_IMAGE?}:${DOCKER_IMAGE_TAG?}
    ports:
      - "${DATABASE_DB_PORT}:3306"
    networks:
      - proxy
      - secure
    volumes:
      - ${DATABASE_CONFIG_DIR}/app_custom.cnf:/opt/bitnami/mariadb/conf/app_custom.cnf:ro
      - ${DATABASE_DATA_DIR}/db_master:/bitnami/mariadb
    environment:
      - MARIADB_REPLICATION_MODE=master
      - MARIADB_REPLICATION_USER=${DATABASE_REPLICATION_USER}
      - MARIADB_REPLICATION_PASSWORD=${DATABASE_REPLICATION_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
      - MARIADB_USER=${DATABASE_USER}
      - MARIADB_PASSWORD=${DATABASE_PASSWORD}
      - MARIADB_DATABASE=${DATABASE_DATABASE_NAME}
    healthcheck:
      test: ["CMD", "/opt/bitnami/scripts/mariadb/healthcheck.sh"]
      interval: 15s
      timeout: 5s
      retries: 6

  mariadb-slave:
    image: ${DOCKER_NAMESPACE}/${DOCKER_IMAGE}:${DOCKER_IMAGE_TAG}
    ports:
      - "3306"
    networks:
      - secure
    depends_on:
      - mariadb-master
    environment:
      - MARIADB_REPLICATION_MODE=slave
      - MARIADB_REPLICATION_USER=${DATABASE_REPLICATION_USER}
      - MARIADB_REPLICATION_PASSWORD=${DATABASE_REPLICATION_PASSWORD}
      - MARIADB_MASTER_HOST=mariadb-master
      - MARIADB_MASTER_PORT_NUMBER=3306
      - MARIADB_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
    healthcheck:
      test: ["CMD", "/opt/bitnami/scripts/mariadb/healthcheck.sh"]
      interval: 15s
      timeout: 5s
      retries: 6
